version: '3'
services:
    node:
        build: docker/node
        restart: always
        volumes:
            - ./:/var/www
        extra_hosts:
            - "registry.npmjs.org:104.16.24.35"
        tty: true

