version: '3'
services:
    https-portal:
        restart: always
        image: steveltn/https-portal:1
        ports:
            - '80:80'
            - '443:443'
        links:
            - wordpress
        environment:
            # change domain
            DOMAINS: '${_DOMAIN_NAME} -> http://wordpress:3080'
            STAGE: 'production'
            FORCE_RENEW: 'true'
            WEBSOCKET: 'true'
            CLIENT_MAX_BODY_SIZE: 0
        volumes:
            - ./.data/https-portal:/var/lib/https-portal
    wordpress:
        image: wordpress
        ports:
            - '3080:80'
        depends_on:
            - mysql
        environment:
            - WORDPRESS_DB_HOST=mysql:3306
            - WORDPRESS_DB_NAME=${_DB_NAME}
            - WORDPRESS_DB_USER=${_DB_USER}
            - WORDPRESS_DB_PASSWORD=${_DB_PASS}
        restart: always
        volumes:
            - ./.data/wordpress:/var/www/html
    mysql:
        image: mysql:5.7
        ports:
            - 3306
        environment:
            - MYSQL_ROOT_PASSWORD=${_DB_PASS}
            - MYSQL_DATABASE=${_DB_NAME}
            - MYSQL_USER=${_DB_USER}
            - MYSQL_PASSWORD=${_DB_PASS}
        restart: always
        volumes:
            - ./.data/mysql:/var/lib/mysql
            - ./utf8.cnf:/etc/mysql/conf.d/utf8.cnf
