version: '3'
services:
    wordpress:
        image: wordpress
        container_name: wordpress
        ports:
            - '80:80'
        depends_on:
            - mysql
        environment:
            - WORDPRESS_DB_HOST=mysql:3306
            - WORDPRESS_DB_NAME=${_DB_NAME}
            - WORDPRESS_DB_USER=${_DB_USER}
            - WORDPRESS_DB_PASSWORD=${_DB_PASS}
        restart: always
        volumes:
            - './data/wordpress:/var/www/html'
        networks:
            - blog_link
    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
            - 3306
        environment:
            - MYSQL_ROOT_PASSWORD=${_DB_PASS}
            - MYSQL_DATABASE=${_DB_NAME}
            - MYSQL_USER=${_DB_USER}
            - MYSQL_PASSWORD=${_DB_PASS}
        restart: always
        volumes:
            - './data/mysql:/var/lib/mysql'
            - './utf8.cnf:/etc/mysql/conf.d/utf8.cnf'
        networks:
            - blog_link
networks:
    blog_link:
        external:
            name: blog_link
